apiVersion: v1
kind: Service
metadata:
  name: devops-tp-svc
  namespace: devops-tp
spec:
  type: NodePort
  selector:
    app: devops-tp
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
