---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Substituer l'image dans le Deployment
      shell: |
        sed -i "s|DOCKER_IMAGE_PLACEHOLDER|{{ lookup('env', 'DOCKER_IMAGE') }}:{{ lookup('env', 'BUILD_NUMBER') }}|g" k8s/deployment.yaml

    - name: Appliquer les manifests Kubernetes
      shell: kubectl apply -f k8s/ --validate=false
      environment:
        KUBECONFIG: /var/jenkins_home/.kube/config

    - name: Attendre que le Deployment soit prêt
      shell: kubectl rollout status deployment/devops-tp-app -n devops-tp --timeout=120s
      environment:
        KUBECONFIG: /var/jenkins_home/.kube/config
